### ISSUE TITLE
How to let a nvim server for multip client?

### ISSUE THREAD

**Issue by lvxingtu** [esensar/neovim-java#108]
I noticed that clients always refer to the same buffer of a server, does some solutions that can let a client  independent with other client.
```java
Socket socket = new Socket("127.0.0.1", 6666);

        RPCConnection localConnection = new TcpSocketRPCConnection(socket);
        NeovimApi api = NeovimApis.getApiForConnection(localConnection);
        codeArea.setOnKeyPressed(e -> {
        api.feedKeys(e.getText(), "i",false);
});

**Comment by esensar** [comment]
Not completely sure what the question is.

If you want to communicate with multiple neovim instances, you need to create separate connectio for each instance and use a separate API instance for each of them.

If you wish to have multiple clients connected to single neovim instance (I assume you meant this) it would be better to use UnixSocket connection. You can see an example in the rplugin example in the repo.

Regarding independent actions on separate buffers, not sure if Neovim API supports it. You can check available methods in the NeovimBufferApi interface.

**Comment by lvxingtu** [comment]
Yes, I mean the second situation. Originally I thought the socket server like a background server and I want to let nvim in another machine, now I know the socket server only a single instance, If I want another instance , I must open another nvim with new listen number, right? So Maybe --embed maybe a good option
