### ISSUE TITLE
RPCClient should allow close and stop sender/listener 

### ISSUE THREAD

**Issue by hkupty** [esensar/neovim-java#76]
Hi,

I'm having issues with the Core-RPC API when I'm using default RPCClient.

Since I don't have control over the created resources, I can't stop the listener. This causes the process to hang when it should exit.

To circumvent that, I'll need to reimplement part of the solution on my end so I can use the executor and object mapper while I have control over both the socket and the listener simply to be able to exit cleanly.

A much simpler solution would be the RPCClient (or RPCStreamer) to expose a close/stop function that both stops the listener and closes the sender.

Cheers,
Henry John Kupty

**Comment by esensar** [comment]
Hi,

RPCConnection implements Closeable. Did you try closing it?
I thought that would be enough. Or is your issue that listener doesn't stop after that?

I can check this later and see if I have a solution for that, either adding close/stop or something else. You can open PR if you want.

Thanks for reporting this.
