### ISSUE TITLE
0.1.12 was published incorrectly

### ISSUE THREAD

**Issue by hkupty** [esensar/neovim-java#78]
I tried using the newest version, but it was missing #77. I checked [the sources](https://repo1.maven.org/maven2/com/ensarsarajcic/neovim/java/core-rpc/0.1.12/) on the jar file.

Maybe you'll need to republish it for the sake of correctness.

**Comment by esensar** [comment]
You are right. I must have forgot to pull your change before releasing 😞 

I have pushed 0.1.13 in the meantime with a fix for API explorer module, it should be available soon and it should also include #77.

**Comment by hkupty** [comment]
It's solved now. Thanks!
